### ISSUE TITLE
Sugestia co do templatek

### ISSUE THREAD

**Issue by Servq** [DruzynaActimela/Kalendarz#1]
Jak wprowadzam zmiany w templatkach, to za każdym razem muszę zatrzymać aplikację, odświeżyć folder i uruchomić aplikację ponownie. Czy nie dałoby się zrobić jakiegoś wykrywania zmian?

**Comment by 4i60r** [comment]
Też zauważyłem, że trochę to kłopotliwe. Coś się wymyśli.

**Comment by 4i60r** [comment]
Dodano możliwość [ładowania templatek z dysku](https://github.com/DruzynaActimela/Kalendarz/commit/5b5a0289452d18a89676f47197c626a82d913f5c)
